numerical_columns:
- Age
- Room Number

cat_col:
- Gender: category
- Blood_Type: category
- Medical_Condition: category
- Date_of_Admission: category
- Doctor: category
- Hospital: category
- Insurance_Provider: category
- Admission_Type: category
- Discharge_Date: category
- Medication: category
- Test_Results: category

columns:
- Age: int
- Gender: category
- Blood_Type: category
- Medical_Condition: category
- Date_of_Admission: category
- Doctor: category
- Hospital: category
- Insurance_Provider: category
- Billing_Amount: double
- Room_Number: int
- Admission_Type: category
- Discharge_Date: category
- Medication: category
- Test_Results: category

drop_columns:
- Name
