numerical columns:
- Age
- Room Number

cat col:
- Gender: category
- Blood Type: category
- Medical Condition: category
- Date of Admission: category
- Doctor: category
- Hospital: category
- Insurance Provider: category
- Admission Type: category
- Discharge Date: category
- Medication: category
- Test Results: category

columns:
- Age: int
- Gender: category
- Blood Type: category
- Medical Condition: category
- Date of Admission: category
- Doctor: category
- Hospital: category
- Insurance Provider: category
- Billing Amount: double
- Room Number: int
- Admission Type: category
- Discharge Date: category
- Medication: category
- Test Results: category

drop columns:
- Name
